Write-Host "DIAGNOSTICANDO WEBHOOK - MENSAJES DEL PROVEEDOR NO LLEGAN"
Write-Host ""
Write-Host "PROBLEMA IDENTIFICADO:"
Write-Host "- Los mensajes ENVIADOS desde la plataforma SÍ funcionan (como 'dd')"
Write-Host "- Los mensajes RECIBIDOS del proveedor NO llegan al webhook"
Write-Host ""
Write-Host "PASOS PARA VERIFICAR:"
Write-Host ""
Write-Host "1. VERIFICAR NGROK:"
Write-Host "   - Abre otra terminal y ejecuta: ngrok http 3001"
Write-Host "   - Copia la URL HTTPS (ej: https://abc123.ngrok.io)"
Write-Host "   - La URL debe ser estable (no cambiar cada vez)"
Write-Host ""
Write-Host "2. VERIFICAR META DEVELOPER CONSOLE:"
Write-Host "   - Ve a: https://developers.facebook.com/apps/"
Write-Host "   - Selecciona tu app de WhatsApp"
Write-Host "   - Ve a WhatsApp > Configuration"
Write-Host "   - Webhook URL debe ser: https://tu-url-ngrok.ngrok.io/api/whatsapp/webhook"
Write-Host "   - Verify Token debe coincidir con tu .env"
Write-Host "   - Subscriptions debe tener marcado: messages, message_deliveries"
Write-Host ""
Write-Host "3. PROBAR WEBHOOK:"
Write-Host "   - En Meta Developer Console, haz clic en 'Test' en la seccion Webhook"
Write-Host "   - Deberia aparecer un mensaje de exito en tu servidor"
Write-Host "   - Si no aparece, el webhook no esta configurado correctamente"
Write-Host ""
Write-Host "4. VERIFICAR NUMERO DE WHATSAPP:"
Write-Host "   - El numero del proveedor debe estar registrado en Meta"
Write-Host "   - Debe tener permisos para enviar mensajes"
Write-Host ""
Write-Host "5. ENVIAR MENSAJE REAL:"
Write-Host "   - Desde el WhatsApp del proveedor (+5491135562673)"
Write-Host "   - Enviar un mensaje al numero de tu app de WhatsApp"
Write-Host "   - Deberia aparecer un log que empiece con [webhook_"
Write-Host ""
Write-Host "SI NO APARECE EL LOG [webhook_, EL PROBLEMA ES LA CONFIGURACION DEL WEBHOOK"
