Write-Host "VERIFICANDO CONFIGURACION DEL WEBHOOK..."
Write-Host ""
Write-Host "1. VERIFICAR NGROK:"
Write-Host "   - Abre otra terminal y ejecuta: ngrok http 3001"
Write-Host "   - Copia la URL HTTPS (ej: https://abc123.ngrok.io)"
Write-Host ""
Write-Host "2. VERIFICAR META DEVELOPER CONSOLE:"
Write-Host "   - Ve a: https://developers.facebook.com/apps/"
Write-Host "   - Selecciona tu app de WhatsApp"
Write-Host "   - Ve a WhatsApp > Configuration"
Write-Host "   - Verifica que el Webhook URL sea: https://tu-url-ngrok.ngrok.io/api/whatsapp/webhook"
Write-Host "   - Verifica que el Verify Token sea: tu_verify_token"
Write-Host "   - Verifica que esten marcados: messages, message_deliveries"
Write-Host ""
Write-Host "3. VERIFICAR SERVIDOR LOCAL:"
Write-Host "   - El servidor debe estar corriendo en puerto 3001"
Write-Host "   - Verifica que no haya errores en la consola"
Write-Host ""
Write-Host "4. PROBAR WEBHOOK:"
Write-Host "   - En Meta Developer Console, haz clic en 'Test' en la seccion Webhook"
Write-Host "   - Deberia aparecer un mensaje de exito en tu servidor"
Write-Host ""
Write-Host "5. VERIFICAR LOGS DEL SERVIDOR:"
Write-Host "   - Busca mensajes que empiecen con: [webhook_"
Write-Host "   - Si no aparecen, el webhook no esta llegando"
