Write-Host "VERIFICANDO ESTADO DE LA BASE DE DATOS..."
Write-Host ""
Write-Host "Ejecuta estas consultas en Supabase Dashboard:"
Write-Host ""
Write-Host "1. VERIFICAR TABLA CONVERSATIONS:"
Write-Host "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'conversations';"
Write-Host ""
Write-Host "2. VERIFICAR ESTRUCTURA DE CONVERSATIONS:"
Write-Host "SELECT column_name, data_type, is_nullable FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'conversations' ORDER BY ordinal_position;"
Write-Host ""
Write-Host "3. VERIFICAR MENSAJES RECIENTES:"
Write-Host "SELECT id, content, message_type, contact_id, user_id, timestamp, conversation_id FROM whatsapp_messages WHERE contact_id = '+5491135562673' ORDER BY timestamp DESC LIMIT 10;"
Write-Host ""
Write-Host "4. VERIFICAR ORDENES RECIENTES:"
Write-Host "SELECT id, order_number, status, created_at, updated_at, provider_id FROM orders WHERE user_id = 'b5a237e6-c9f9-4561-af07-a1408825ab50' ORDER BY created_at DESC LIMIT 5;"
Write-Host ""
Write-Host "5. VERIFICAR PROVEEDORES:"
Write-Host "SELECT id, name, phone, user_id FROM providers WHERE phone = '+5491135562673';"
Write-Host ""
Write-Host "6. VERIFICAR CONVERSACIONES ACTIVAS:"
Write-Host "SELECT id, contact_id, user_id, created_at, updated_at FROM conversations WHERE contact_id = '+5491135562673' ORDER BY updated_at DESC LIMIT 5;"
Write-Host ""
Write-Host "DIAGNOSTICO:"
Write-Host "- Si la tabla conversations no existe, hay que crearla"
Write-Host "- Si no hay conversation_id en los mensajes, hay que vincularlos"
Write-Host "- Si no hay conversaciones activas, hay que crearlas"
