Write-Host "RECREANDO TABLA CONVERSATIONS..."
Write-Host ""
Write-Host "Ejecuta este script en Supabase Dashboard:"
Write-Host ""
Write-Host "1. Ve a Supabase Dashboard > SQL Editor"
Write-Host "2. Copia y pega el contenido de: temporario/recreate-conversations-table.sql"
Write-Host "3. Ejecuta el script"
Write-Host ""
Write-Host "El script hara lo siguiente:"
Write-Host "- Verificara si existe la tabla conversations"
Write-Host "- La creara si no existe"
Write-Host "- Creara los indices necesarios"
Write-Host "- Configurara las politicas de seguridad"
Write-Host "- Creara conversaciones para contactos existentes"
Write-Host "- Vinculera mensajes existentes con conversaciones"
Write-Host ""
Write-Host "Despues de ejecutar el script, prueba enviar un mensaje real del proveedor."
