Write-Host "CONFIGURANDO WEBHOOK CON NGROK..."
Write-Host ""
Write-Host "NGROK ESTA CORRIENDO EN: https://f7e3caa406f"
Write-Host ""
Write-Host "PASOS PARA CONFIGURAR EL WEBHOOK:"
Write-Host ""
Write-Host "1. Ve a Meta Developer Console:"
Write-Host "   https://developers.facebook.com/apps/"
Write-Host ""
Write-Host "2. Selecciona tu app de WhatsApp"
Write-Host ""
Write-Host "3. Ve a WhatsApp > Configuration"
Write-Host ""
Write-Host "4. Configura el Webhook:"
Write-Host "   - Webhook URL: https://f7e3caa406f.ngrok.io/api/whatsapp/webhook"
Write-Host "   - Verify Token: tu_verify_token (debe coincidir con tu .env)"
Write-Host ""
Write-Host "5. Marca las Subscriptions:"
Write-Host "   - messages"
Write-Host "   - message_deliveries"
Write-Host ""
Write-Host "6. Haz clic en 'Verify and Save'"
Write-Host ""
Write-Host "7. Prueba el webhook:"
Write-Host "   - Haz clic en 'Test' en la seccion Webhook"
Write-Host "   - Deberia aparecer un mensaje de exito en tu servidor"
Write-Host ""
Write-Host "8. Envia un mensaje real:"
Write-Host "   - Desde el WhatsApp del proveedor (+5491135562673)"
Write-Host "   - Al numero de tu app de WhatsApp"
Write-Host "   - Deberia aparecer un log que empiece con [webhook_"
Write-Host ""
Write-Host "NOTA: La URL de ngrok puede cambiar si reinicias ngrok."
Write-Host "Si cambia, actualiza la URL en Meta Developer Console."

